"""Generate `nagent_tools.py` — the sandbox-side stub that calls back to
the parent process via UDS.

The stub is pure-client: it connects to a Unix domain socket, sends a JSON
request, and reads one JSON response. It CANNOT forge responses (it is not
the server), which closes the forgery path that file-based RPC had.
"""

from __future__ import annotations

import json
from typing import Any


_STUB_TEMPLATE = '''\
"""Auto-generated by n-agent sandbox stub_generator. Do not edit."""
import json
import socket
import sys
from typing import Any

%(all_decl)s

_RPC_SOCKET_PATH = %(socket_path)r
_RPC_TIMEOUT = 60.0


def _rpc(name: str, arguments: dict) -> dict:
    payload = json.dumps({"name": name, "arguments": arguments}).encode("utf-8")
    try:
        sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        sock.settimeout(_RPC_TIMEOUT)
        sock.connect(_RPC_SOCKET_PATH)
        sock.sendall(payload)
        sock.shutdown(socket.SHUT_WR)
        chunks = []
        while True:
            data = sock.recv(8192)
            if not data:
                break
            chunks.append(data)
        sock.close()
    except OSError as exc:
        return {"status": "error", "error": f"rpc transport failed: {exc}"}
    raw = b"".join(chunks)
    try:
        return json.loads(raw.decode("utf-8"))
    except Exception as exc:
        return {"status": "error", "error": f"rpc decode failed: {exc}"}


class _ToolProxy:
    def __init__(self, name: str) -> None:
        self._name = name

    def __call__(self, **kwargs: Any) -> dict:
        return _rpc(self._name, kwargs)


def _install(enabled_tools):
    for _t in enabled_tools:
        globals()[_t] = _ToolProxy(_t)


_ENABLED = %(enabled_tools)r
_install(_ENABLED)
'''


def generate_stub(enabled_tools: list[str], rpc_socket_path: str) -> str:
    """Generate the `nagent_tools.py` source for sandboxed code to import.

    Args:
        enabled_tools: callback tool names to expose (already narrowed per-call).
        rpc_socket_path: absolute path to the UDS socket. For Local, this is a
            host path under scratch_dir. For Docker, this is the *container-side*
            path `/scratch/<safe>/call-<uuid>/rpc.sock` (the same file is
            bind-mounted from the host staging dir).
    """
    tools = list(enabled_tools)
    # __all__ restricts `from nagent_tools import *` to only callback tool
    # names, preventing _rpc/_ToolProxy/_ENABLED/typing.Any from leaking into
    # the user script's namespace.
    all_decl = "__all__ = " + repr(tools)
    return _STUB_TEMPLATE % {
        "socket_path": rpc_socket_path,
        "enabled_tools": tools,
        "all_decl": all_decl,
    }
